// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace EventsPlanner.Models
{
    [Table("Stand")]
    public partial class Stand
    {
        public Stand()
        {
            Bookings = new HashSet<Booking>();
        }

        [Key]
        [Column("Stand_No")]
        public int StandNo { get; set; }
        [Key]
        [Column("Event_No")]
        public int EventNo { get; set; }
        [StringLength(1)]
        public string Types { get; set; }
        public double Price { get; set; }

        [ForeignKey(nameof(EventNo))]
        [InverseProperty(nameof(Event.Stands))]
        public virtual Event EventNoNavigation { get; set; }
        [InverseProperty(nameof(Booking.Stand))]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}